# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink:        pretty

# Setup
title:            Saving Private Developer
tagline:          'Saving Private Developer'
description:      "Gaurav Rane's weekly blog about programming, debugging, hacking, software and technology."
url:              https://www.savingprivatedeveloper.com/
baseurl:          /

author:
  name:           'Gaurav Rane'
  email:          gaurav.v.rane@gmail.com
  twitter:        https://twitter.com/me_grane

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/gauravrane2212/saving-private-developer
